"""005 -- delegation dispatched under its own provisioned uid, trusted only after a real check-in.

See `lab/005-delegation-with-uid-cgroup.md` for the hypothesis (with explicit null), method, and
analysis. This script runs the experiment and writes results under `out/005/`.

Combines 002 (delegation reduces to the same Gate/Decision/Executor primitive) with 004
(uid+cgroup as a real execution class), and adds the one mechanism neither needed on its own: a
real check-in protocol. 004's effect was a hardcoded script the Executor wrote and trusted the
instant it was spawned under the right uid -- there was nothing for the spawned process to prove,
because the Executor already knew exactly what it would do. A *delegated* unit of work is
different: the broker hands off to a separately-dispatched sub-agent and only finds out it's
legitimate by independently verifying it, the same way HISTORY.md's account of v1 already
identified this as the natural next composition needing the check-in protocol.

Check-in mechanism: a nonce (generated by the broker, handed to the child only via an inherited
pipe fd -- never argv, which is world-readable via /proc/<pid>/cmdline on real Linux, a lesson
HISTORY.md records from v1 the hard way) plus SO_PEERCRED (the kernel's own record of which real
uid actually holds the other end of a Unix socket connection, not anything the connecting process
can assert). Both must agree before the broker treats the delegated sub-agent as trustworthy enough
to let it perform its actual effect, or to trust the effect it already performed.

Built entirely fresh -- no import, copy, or "remembering" of any prior version of this mechanism
(v1's checkin.py, or the earlier lab/004 built before this repo's archive was deleted). Needs real
root on real Linux for the same reasons 004 does; refuses cleanly everywhere else.

Run (from macOS, will refuse -- confirms the refusal path)::

    cd /Users/shunhonda/dev/siphonophore
    python3 lab/005_delegation_with_uid_cgroup.py

Run for real, as root, on colima::

    colima ssh -- bash -c "cd /Users/shunhonda/dev/siphonophore && sudo python3 lab/005_delegation_with_uid_cgroup.py"
"""
from __future__ import annotations

import hashlib
import hmac
import json
import os
import pwd
import secrets
import shutil
import socket
import struct
import subprocess
import sys
import tempfile
import uuid
from dataclasses import dataclass
from pathlib import Path

OUT = Path(__file__).parent / "out" / "005"

UID_RANGE_START = 63000
UID_RANGE_END = 63999
CGROUP_ROOT = Path("/sys/fs/cgroup/siphonophore-exp005")


def require_real_root_linux() -> None:
    if sys.platform != "linux":
        sys.stderr.write(
            "REFUSED: this experiment requires real Linux (uid/cgroup provisioning, SO_PEERCRED "
            f"are Linux-specific). Detected sys.platform={sys.platform!r}. Run it on colima:\n"
            "  colima ssh -- bash -c \"cd /Users/shunhonda/dev/siphonophore && "
            "sudo python3 lab/005_delegation_with_uid_cgroup.py\"\n"
        )
        sys.exit(1)
    if os.geteuid() != 0:
        sys.stderr.write(
            f"REFUSED: this experiment requires real root. Detected euid={os.geteuid()}. Re-run with sudo.\n"
        )
        sys.exit(1)
    if not Path("/sys/fs/cgroup/cgroup.controllers").exists():
        sys.stderr.write("REFUSED: cgroup v2 unified hierarchy not detected.\n")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Core primitives -- same shape as 001-004
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Intent:
    kind: str  # "write_file" | "delegate"
    principal_id: str
    intent_id: str
    payload: dict
    consequence: str  # "low" | "high" | "privileged"


@dataclass(frozen=True)
class Decision:
    intent_id: str
    principal_id: str
    kind: str
    permitted: bool
    execution_class: str
    token: str


class Gate:
    CONSEQUENCE_TO_CLASS = {"low": "same_process", "high": "separate_process", "privileged": "uid_cgroup"}

    def __init__(self) -> None:
        self._secret = secrets.token_bytes(32)

    def _canonical(self, intent_id, principal_id, kind, permitted, execution_class) -> bytes:
        return f"{intent_id}:{principal_id}:{kind}:{permitted}:{execution_class}".encode("utf-8")

    def _mint(self, intent_id, principal_id, kind, permitted, execution_class) -> str:
        msg = self._canonical(intent_id, principal_id, kind, permitted, execution_class)
        return hmac.new(self._secret, msg, hashlib.sha256).hexdigest()

    def submit(self, intent: Intent) -> Decision:
        permitted = self._policy(intent)
        execution_class = self.CONSEQUENCE_TO_CLASS.get(intent.consequence, "same_process")
        token = self._mint(intent.intent_id, intent.principal_id, intent.kind, permitted, execution_class)
        return Decision(
            intent_id=intent.intent_id, principal_id=intent.principal_id, kind=intent.kind,
            permitted=permitted, execution_class=execution_class, token=token,
        )

    def verify(self, decision: Decision) -> bool:
        expected = self._mint(
            decision.intent_id, decision.principal_id, decision.kind, decision.permitted, decision.execution_class
        )
        return hmac.compare_digest(expected, decision.token)

    def _policy(self, intent: Intent) -> bool:
        return intent.kind in ("write_file", "delegate") and intent.consequence in ("low", "high", "privileged")


class GateViolation(PermissionError):
    pass


class ProvisioningError(RuntimeError):
    pass


class CheckinError(RuntimeError):
    pass


# ---------------------------------------------------------------------------
# uid+cgroup provisioning -- fresh, self-contained, same shape as 004
# ---------------------------------------------------------------------------


def _run(cmd: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True)


def _find_free_uid() -> int:
    taken = {pw.pw_uid for pw in pwd.getpwall()}
    for candidate in range(UID_RANGE_START, UID_RANGE_END + 1):
        if candidate not in taken:
            return candidate
    raise ProvisioningError(f"no free uid in reserved range [{UID_RANGE_START}, {UID_RANGE_END}]")


def provision_ephemeral_user(execution_id: str) -> tuple[str, int, int]:
    uid = _find_free_uid()
    username = f"sipho5-{execution_id[:8]}"
    result = _run([
        "useradd", "--no-create-home", "--shell", "/usr/sbin/nologin", "--uid", str(uid),
        "--comment", "siphonophore ephemeral execution identity (experiment 005)", username,
    ])
    if result.returncode != 0:
        raise ProvisioningError(f"useradd failed (rc={result.returncode}): {result.stderr.strip()}")
    entry = pwd.getpwnam(username)
    if entry.pw_uid != uid:
        raise ProvisioningError(f"useradd created uid={entry.pw_uid}, expected {uid}")
    return username, entry.pw_uid, entry.pw_gid


def release_ephemeral_user(username: str) -> None:
    result = _run(["userdel", username])
    if result.returncode != 0:
        raise ProvisioningError(f"userdel failed (rc={result.returncode}): {result.stderr.strip()}")


def provision_cgroup(execution_id: str) -> Path:
    CGROUP_ROOT.mkdir(parents=True, exist_ok=True)
    cg = CGROUP_ROOT / f"exec-{execution_id}"
    cg.mkdir(parents=True, exist_ok=False)
    return cg


def add_pid_to_cgroup(cgroup_path: Path, pid: int) -> None:
    (cgroup_path / "cgroup.procs").write_text(str(pid))


def read_cgroup_procs(cgroup_path: Path) -> set[int]:
    text = (cgroup_path / "cgroup.procs").read_text()
    return {int(line) for line in text.split() if line.strip()}


def release_cgroup(cgroup_path: Path) -> None:
    remaining = read_cgroup_procs(cgroup_path)
    if remaining:
        raise ProvisioningError(f"refusing to release cgroup with live members: {remaining}")
    cgroup_path.rmdir()


def read_real_uid_from_proc(pid: int) -> int:
    status_text = Path(f"/proc/{pid}/status").read_text()
    for line in status_text.splitlines():
        if line.startswith("Uid:"):
            return int(line.split()[1])
    raise ProvisioningError(f"no Uid: line in /proc/{pid}/status")


def _read_peer_uid(conn: socket.socket) -> int:
    """The kernel's own record of which real uid holds the other end of this Unix socket
    connection -- SO_PEERCRED, not anything the connecting process sent or could spoof."""
    creds = conn.getsockopt(socket.SOL_SOCKET, socket.SO_PEERCRED, struct.calcsize("3i"))
    _pid, uid, _gid = struct.unpack("3i", creds)
    return uid


# ---------------------------------------------------------------------------
# The sub-agent's own program -- a real, separate process
# ---------------------------------------------------------------------------

_SUBAGENT_PROGRAM = """
import json, os, socket, sys

socket_path, path, content, nonce_fd = sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4])
nonce = os.read(nonce_fd, 4096).decode()
os.close(nonce_fd)

sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
sock.connect(socket_path)
sock.sendall(nonce.encode())
response = sock.recv(1)
sock.close()

if response != b"1":
    print(json.dumps({"checked_in": False, "pid": os.getpid()}))
    sys.exit(1)

with open(path, "w") as f:
    f.write(content)

print(json.dumps({"checked_in": True, "pid": os.getpid(), "self_reported_uid": os.getuid()}))
"""

_NEVER_CHECKS_IN_PROGRAM = "import time\ntime.sleep(30)\n"


class Executor:
    def __init__(self, gate: Gate) -> None:
        self._gate = gate

    def execute(self, decision: Decision, intent: Intent, *, _subagent_program: str = _SUBAGENT_PROGRAM,
                _checkin_timeout: float = 5.0) -> dict:
        if decision.intent_id != intent.intent_id or decision.kind != intent.kind:
            raise GateViolation("decision does not correspond to this intent")
        if not self._gate.verify(decision):
            raise GateViolation("decision failed Gate verification -- forged, tampered, or downgraded")
        if not decision.permitted:
            raise GateViolation("decision denies this intent")

        if intent.kind == "delegate" and decision.execution_class == "uid_cgroup":
            return self._execute_delegate_uid_cgroup(
                decision, intent, subagent_program=_subagent_program, checkin_timeout=_checkin_timeout
            )
        raise GateViolation(f"no executor handler for kind={intent.kind!r} execution_class={decision.execution_class!r}")

    def _execute_delegate_uid_cgroup(self, decision: Decision, intent: Intent, *, subagent_program: str,
                                      checkin_timeout: float) -> dict:
        execution_id = decision.intent_id
        path = intent.payload["path"]
        content = intent.payload["content"]
        observations: dict = {}

        username, uid, gid = provision_ephemeral_user(execution_id)
        observations["provisioned_uid"] = uid
        cgroup_path = provision_cgroup(execution_id)
        observations["cgroup_path"] = str(cgroup_path)

        socket_path = f"/tmp/sipho-005-checkin-{execution_id}.sock"
        if os.path.exists(socket_path):
            os.unlink(socket_path)
        listener = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        listener.bind(socket_path)
        # bind() creates the socket with the broker's own (root) umask permissions -- a
        # provisioned, unprivileged uid has no write access to connect() to it otherwise. Widening
        # to 0o777 does not weaken verification: the actual security boundary below is the
        # nonce+SO_PEERCRED check, which rejects anything that doesn't match regardless of how it
        # reached accept() at all.
        os.chmod(socket_path, 0o777)
        listener.listen(1)
        listener.settimeout(checkin_timeout)

        nonce = secrets.token_hex(32)
        read_fd, write_fd = os.pipe()
        os.write(write_fd, nonce.encode())
        os.close(write_fd)

        def _drop_privileges() -> None:
            os.setgroups([])
            os.setgid(gid)
            os.setuid(uid)

        proc: subprocess.Popen | None = None
        checkin: dict = {"received": False}
        try:
            try:
                proc = subprocess.Popen(
                    [sys.executable, "-c", subagent_program, socket_path, path, content, str(read_fd)],
                    pass_fds=(read_fd,),
                    preexec_fn=_drop_privileges,
                    stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
                )
                os.close(read_fd)
                add_pid_to_cgroup(cgroup_path, proc.pid)
                observations["cgroup_members_before_checkin"] = sorted(read_cgroup_procs(cgroup_path))

                try:
                    conn, _ = listener.accept()
                except (socket.timeout, TimeoutError):
                    checkin["timed_out"] = True
                    raise CheckinError(f"sub-agent {execution_id} never checked in within {checkin_timeout}s")

                with conn:
                    presented_nonce = conn.recv(4096).decode()
                    peer_uid = _read_peer_uid(conn)
                    real_uid_from_proc = read_real_uid_from_proc(proc.pid)  # second, independent kernel source
                    checkin["received"] = True
                    checkin["presented_nonce_matches"] = hmac.compare_digest(presented_nonce, nonce)
                    checkin["peer_uid_from_so_peercred"] = peer_uid
                    checkin["peer_uid_from_proc_status"] = real_uid_from_proc
                    checkin["peer_uid_matches_provisioned"] = peer_uid == uid
                    checkin["two_kernel_sources_agree"] = peer_uid == real_uid_from_proc
                    verified = (
                        checkin["presented_nonce_matches"]
                        and checkin["peer_uid_matches_provisioned"]
                        and checkin["two_kernel_sources_agree"]
                    )
                    checkin["verified"] = verified
                    conn.sendall(b"1" if verified else b"0")

                if not verified:
                    raise CheckinError(f"sub-agent {execution_id} failed check-in verification")

                stdout, stderr = proc.communicate(timeout=10)
                observations["child_returncode"] = proc.returncode
                if proc.returncode != 0:
                    raise ProvisioningError(f"sub-agent exited nonzero after check-in: {stderr!r}")
                observations["child_self_report"] = json.loads(stdout.strip())
                observations["checkin"] = checkin

                return {
                    "effect": "delegate",
                    "execution_class": "uid_cgroup",
                    "acting_pid": proc.pid,
                    "observations": observations,
                }
            finally:
                if proc is not None and proc.poll() is None:
                    proc.kill()
                    try:
                        proc.wait(timeout=5)
                    except subprocess.TimeoutExpired:
                        pass
                for fd in (read_fd, write_fd):
                    try:
                        os.close(fd)
                    except OSError:
                        pass
                listener.close()
                if os.path.exists(socket_path):
                    os.unlink(socket_path)
        finally:
            # Release on EVERY exit path (success, check-in failure, timeout, exception) -- 004's
            # write-up named exactly this as an unfixed gap (release logic only reached on the
            # success path, leaking a real user+cgroup on a mid-execution failure). Fixed here by
            # putting release in this outer finally, wrapping the whole provision-through-dispatch
            # sequence, not just the fd/process cleanup.
            try:
                release_cgroup(cgroup_path)
                observations["cgroup_released"] = not cgroup_path.exists()
            except ProvisioningError:
                observations["cgroup_released"] = False
            release_ephemeral_user(username)
            try:
                pwd.getpwnam(username)
                observations["user_released"] = False
            except KeyError:
                observations["user_released"] = True


# ---------------------------------------------------------------------------
# Experiment
# ---------------------------------------------------------------------------


def run() -> dict:
    OUT.mkdir(parents=True, exist_ok=True)
    workdir = Path(tempfile.mkdtemp(prefix="sipho-005-"))
    os.chmod(workdir, 0o777)  # same reason as 004: the provisioned uid needs to write here
    results: dict = {"workdir": str(workdir), "broker_pid": os.getpid(), "broker_uid": os.getuid()}

    gate = Gate()
    executor = Executor(gate)

    # --- Predicate A: happy path -- mediated delegation succeeds, sub-agent checked in for real,
    # two independent kernel sources (SO_PEERCRED, /proc/<pid>/status) agree with each other and
    # with the child's own self-report, and the effect is confirmed on disk. -------------------
    a_path = workdir / "delegated_effect.txt"
    a_content = f"written by a checked-in delegate, nonce={uuid.uuid4().hex}"
    a_intent = Intent(
        kind="delegate", principal_id="principal-alice", intent_id=str(uuid.uuid4()),
        payload={"path": str(a_path), "content": a_content}, consequence="privileged",
    )
    a_decision = gate.submit(a_intent)
    assert a_decision.execution_class == "uid_cgroup"
    a_effect = executor.execute(a_decision, a_intent)
    a_obs = a_effect["observations"]
    a_checkin = a_obs["checkin"]

    results["predicate_a_happy_path"] = {
        "file_content_matches": a_path.exists() and a_path.read_text() == a_content,
        "checkin_verified": a_checkin["verified"],
        "provisioned_uid": a_obs["provisioned_uid"],
        "broker_uid": results["broker_uid"],
        "provisioned_uid_differs_from_broker": a_obs["provisioned_uid"] != results["broker_uid"],
        "so_peercred_matches_provisioned": a_checkin["peer_uid_matches_provisioned"],
        "so_peercred_matches_proc_status": a_checkin["two_kernel_sources_agree"],
        "self_report_uid_matches_kernel": (
            a_obs["child_self_report"]["self_reported_uid"] == a_checkin["peer_uid_from_so_peercred"]
        ),
        "cgroup_released": a_obs["cgroup_released"],
        "user_released": a_obs["user_released"],
    }

    # --- Predicate B: impersonation -- a connection presenting the WRONG nonce is refused, and
    # the delegation is reported as failed, not silently trusted. -------------------------------
    b_path = workdir / "impersonation_effect.txt"
    b_intent = Intent(
        kind="delegate", principal_id="principal-mallory", intent_id=str(uuid.uuid4()),
        payload={"path": str(b_path), "content": "should never appear"}, consequence="privileged",
    )
    b_decision = gate.submit(b_intent)

    _WRONG_NONCE_PROGRAM = _SUBAGENT_PROGRAM.replace(
        "nonce = os.read(nonce_fd, 4096).decode()",
        "os.read(nonce_fd, 4096)\nnonce = 'a-completely-wrong-guessed-nonce'",
    )
    b_failed = False
    b_error = None
    try:
        executor.execute(b_decision, b_intent, _subagent_program=_WRONG_NONCE_PROGRAM)
    except CheckinError as exc:
        b_failed = True
        b_error = str(exc)

    users_after_b = {pw.pw_name for pw in pwd.getpwall()}
    results["predicate_b_impersonation_refused"] = {
        "raised_checkin_error": b_failed,
        "error": b_error,
        "target_file_absent": not b_path.exists(),
        "no_leftover_sipho5_user": not any(u.startswith("sipho5-") for u in users_after_b),
    }

    # --- Predicate C: a sub-agent that never checks in at all times out, is killed, and cleanup
    # still runs (release-on-every-exit-path, the exact gap 004 named and this experiment fixes). -
    c_path = workdir / "never_checks_in_effect.txt"
    c_intent = Intent(
        kind="delegate", principal_id="principal-carol", intent_id=str(uuid.uuid4()),
        payload={"path": str(c_path), "content": "should never appear"}, consequence="privileged",
    )
    c_decision = gate.submit(c_intent)
    c_failed = False
    c_error = None
    try:
        executor.execute(c_decision, c_intent, _subagent_program=_NEVER_CHECKS_IN_PROGRAM, _checkin_timeout=1.5)
    except CheckinError as exc:
        c_failed = True
        c_error = str(exc)

    users_after_c = {pw.pw_name for pw in pwd.getpwall()}
    cgroups_after_c = set(CGROUP_ROOT.iterdir()) if CGROUP_ROOT.exists() else set()
    results["predicate_c_never_checks_in_times_out"] = {
        "raised_checkin_error": c_failed,
        "error": c_error,
        "target_file_absent": not c_path.exists(),
        "no_leftover_sipho5_user": not any(u.startswith("sipho5-") for u in users_after_c),
        "no_leftover_exec_cgroup": not any(p.name.startswith(f"exec-{c_intent.intent_id}") for p in cgroups_after_c),
    }

    # --- Predicate D: forged Decision (never through Gate.submit()) is refused before any
    # provisioning happens at all -- no user, no cgroup, no socket, no subprocess. ---------------
    d_path = workdir / "forged.txt"
    d_intent = Intent(
        kind="delegate", principal_id="principal-eve", intent_id=str(uuid.uuid4()),
        payload={"path": str(d_path), "content": "should never appear"}, consequence="privileged",
    )
    d_forged = Decision(
        intent_id=d_intent.intent_id, principal_id=d_intent.principal_id, kind=d_intent.kind,
        permitted=True, execution_class="uid_cgroup", token="beadfeed" * 8,
    )
    users_before_d = {pw.pw_name for pw in pwd.getpwall()}
    d_refused = False
    try:
        executor.execute(d_forged, d_intent)
    except GateViolation:
        d_refused = True
    users_after_d = {pw.pw_name for pw in pwd.getpwall()}

    results["predicate_d_forged_refused_no_provisioning"] = {
        "refused": d_refused,
        "target_file_absent": not d_path.exists(),
        "no_new_users_provisioned": users_after_d == users_before_d,
    }

    return results


def main() -> int:
    require_real_root_linux()
    results = run()

    out_path = OUT / "results.json"
    out_path.write_text(json.dumps(results, indent=2, default=str))
    print(f"wrote {out_path}")
    print(json.dumps(results, indent=2, default=str))

    a = results["predicate_a_happy_path"]
    b = results["predicate_b_impersonation_refused"]
    c = results["predicate_c_never_checks_in_times_out"]
    d = results["predicate_d_forged_refused_no_provisioning"]

    checks = [
        ("happy path: file content matches", a["file_content_matches"] is True),
        ("happy path: check-in verified", a["checkin_verified"] is True),
        ("happy path: provisioned uid differs from broker", a["provisioned_uid_differs_from_broker"] is True),
        ("happy path: SO_PEERCRED matches provisioned uid", a["so_peercred_matches_provisioned"] is True),
        ("happy path: SO_PEERCRED matches /proc/status", a["so_peercred_matches_proc_status"] is True),
        ("happy path: self-report matches kernel ground truth", a["self_report_uid_matches_kernel"] is True),
        ("happy path: cgroup released", a["cgroup_released"] is True),
        ("happy path: user released", a["user_released"] is True),
        ("impersonation: CheckinError raised", b["raised_checkin_error"] is True),
        ("impersonation: target file absent", b["target_file_absent"] is True),
        ("impersonation: no leftover user", b["no_leftover_sipho5_user"] is True),
        ("timeout: CheckinError raised", c["raised_checkin_error"] is True),
        ("timeout: target file absent", c["target_file_absent"] is True),
        ("timeout: no leftover user", c["no_leftover_sipho5_user"] is True),
        ("timeout: no leftover cgroup", c["no_leftover_exec_cgroup"] is True),
        ("forged: refused", d["refused"] is True),
        ("forged: target file absent", d["target_file_absent"] is True),
        ("forged: no provisioning side effects", d["no_new_users_provisioned"] is True),
    ]
    ok = True
    for name, passed in checks:
        print(f"[{'PASS' if passed else 'FAIL'}] {name}")
        ok = ok and passed

    shutil.rmtree(results["workdir"], ignore_errors=True)

    if not ok:
        print("HYPOTHESIS NOT SUPPORTED", file=sys.stderr)
        return 1
    print("HYPOTHESIS SUPPORTED")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
